### ISSUE TITLE
Request for a GET API (Angus-to-Pizza Interface) 

### ISSUE THREAD

**Issue by angushtlam** [mpoegel/rsvp.pizza#2]
Hello,

I would like to propose a new JSON GET endpoint that returns data on the page render endpoint in the format of:

```
{
    pizza: [
        {
              timestamp: ISO timestamp,
              attendees: number
        }
    ]
}
```

**Comment by mpoegel** [comment]
API has been released with v0.10 and is documented on the [wiki](https://github.com/mpoegel/rsvp.pizza/wiki/API).
